### ISSUE TITLE
Disable submit button without playlist 

### ISSUE THREAD

**Issue by sam9116** [taver-ca/Taver_Hackathon#58]
this should not be clickable without an url

![image](https://github.com/taver-ca/Taver_Hackathon/assets/2815262/ee238b8b-3e53-4104-bfc0-5d071025e0df)

**Comment by priyamannur** [comment]
![disabled](https://github.com/user-attachments/assets/30182760-9ccb-4bf7-a438-ef863b5d9f27)
![enabled](https://github.com/user-attachments/assets/25c7c49f-2014-46f9-bf3d-fb4ed5a34c23)
Would this be correct?

**Comment by sam9116** [comment]
@priyamannur I think the string will need to include **_https://open.spotify.com/playlist/_**

**Comment by priyamannur** [comment]
Ok, I think I can solve this, could you please assign me this?

**Comment by sam9116** [comment]
sure, I will also send you the environment variables to run this project locally

**Comment by sam9116** [comment]
@priyamannur do you have an email I can send the environment variables to?

**Comment by priyamannur** [comment]
yess, @priyamannur14608@gmail.com

**Comment by sam9116** [comment]
closed with https://github.com/taver-ca/Taver_Hackathon/commit/44d28b35ba8bfddf5065682cf97189ad7e780f35
