### ISSUE TITLE
Add option to clear all

### ISSUE THREAD

**Issue by sam9116** [taver-ca/Taver_Hackathon#74]
Delete all artist suggestions and scheduled concerts

**Comment by priyamannur** [comment]
Heyy, since the google maps are not being displayed, it is difficult to understand what this intends.
So wanted to clarify certain things.
When you initially load the page, do all the concerts get displayed on the map?
And, that,  by adding a 'delete all' feature, we have to clear?

**Comment by sam9116** [comment]
What I meant was deleting all the chosen artist concerts at once, instead of deleting them one by one

![image](https://github.com/user-attachments/assets/63010819-dba0-4783-b5d1-7905c0c7c371)

**Comment by sankshaypusa** [comment]
Hi sam  you can create an DeleteAllIcon component  which can delete all the selected users detail at once ,I just did that ,may I know is that correct?
<img width="1362" alt="Screenshot 2024-07-23 at 5 44 12 PM" src="https://github.com/user-attachments/assets/b2753679-d8ed-4ade-bb98-758f6c1154f9">

**Comment by sam9116** [comment]
> Hi sam you can create an DeleteAllIcon component which can delete all the selected users detail at once ,I just did that ,may I know is that correct? <img alt="Screenshot 2024-07-23 at 5 44 12 PM" width="1362" src="https://private-user-images.githubusercontent.com/55947622/351515306-b2753679-d8ed-4ade-bb98-758f6c1154f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzUxNTAsIm5iZiI6MTcyMTc3NDg1MCwicGF0aCI6Ii81NTk0NzYyMi8zNTE1MTUzMDYtYjI3NTM2NzktZDhlZC00YWRlLWJiOTgtNzU4ZjZjMTE1NGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmQxMTY3NTAzZGIzNjQyYjgxMjQwNjgxZDNlYjE2ZmFjYjJjZGRjNmYxM2MxYjYyZDE4OWEwZTE4ZDgwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WUur8XguKw9wCKrpLYmoIXbz3ctvHHr7KXzttpi9zl0">

That would be, yes

**Comment by sam9116** [comment]
completed with commit https://github.com/taver-ca/Taver_Hackathon/commit/89c29fc65c671f62e08280a6bebba2baf0a194b6
