### ISSUE TITLE
Show the concert limit (0/5) at the very beginning 

### ISSUE THREAD

**Issue by sam9116** [taver-ca/Taver_Hackathon#84]
as part of demo feedback https://github.com/taver-ca/Taver_Hackathon/issues/72

people felt surprised when the hard limit was hit

add a count on top of concert list as shown in screenshot.

![image](https://github.com/user-attachments/assets/2753f4fd-0d25-4d9b-93dc-d0b81aa4ddb2)

So user won't be surprised when they hit the 5 artist limit when it comes

**Comment by GeorgiosDrivas** [comment]
Hello @sam9116! I would like to work on this issue.

**Comment by sam9116** [comment]
@GeorgiosDrivas sure! I will also send you the environment variable you will need to test this locally

**Comment by sam9116** [comment]
do you have an email I can send the environment variable to?

**Comment by GeorgiosDrivas** [comment]
Hello Sam, everything works perfect with the environment variable you sent me. I would like to make sure the UI is approved before making any pull requests, just to avoid making changes later. Attached you will find an image of the feature.
![test](https://github.com/user-attachments/assets/bcfcb3c9-f2d0-4b66-b974-ecd9cba43a47)

**Comment by sam9116** [comment]
@GeorgiosDrivas that UI is good, I approve 👍

**Comment by sam9116** [comment]
Closed with https://github.com/taver-ca/Taver_Hackathon/commit/87553ab7c5d98ebd3012498feb533395dc3997de
