### ISSUE TITLE
Tell user when they enter an invalid spotify playlist url

### ISSUE THREAD

**Issue by sam9116** [taver-ca/Taver_Hackathon#85]
https://github.com/orgs/taver-ca/discussions/83

add error handling to this 
![image](https://github.com/user-attachments/assets/a926b318-3ae8-48d1-83e4-cb328c6b58f9)

**Comment by jeevikasirwani** [comment]
I can try to solve this.

**Comment by sam9116** [comment]
sure, I will assign you and send you the environment variables you will need to run the website locally

**Comment by sam9116** [comment]
closed with https://github.com/taver-ca/Taver_Hackathon/commit/582a14b3d554227eb49dc18390a0e53b4a8da701

**Comment by sam9116** [comment]
@jeevikasirwani you can use the built in `helperText` in MUI TextField next time you want to write an error message 
![image](https://github.com/user-attachments/assets/1bbddff4-ded3-40f2-9c80-29166ae6d466)

**Comment by jeevikasirwani** [comment]
sure changing it

> @jeevikasirwani you can use the built in `helperText` in MUI TextField next time you want to write an error message ![image](https://private-user-images.githubusercontent.com/2815262/352818097-1bbddff4-ded3-40f2-9c80-29166ae6d466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzYzNDksIm5iZiI6MTcyMjE3NjA0OSwicGF0aCI6Ii8yODE1MjYyLzM1MjgxODA5Ny0xYmJkZGZmNC1kZWQzLTQwZjItOWM4MC0yOTE2NmFlNmQ0NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTQxNDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNmMzllOWU0NjI1ZGNiYzc1NjA2ZTg1NjdjOGExN2Q3NWMwYjVhYjU0NzVlMGMxOWI2MDNlODljMGQ3ODRiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ziEaXW1wZ-zNb5FMidvYsY-Cxzk9neP4NCKs3-BGubM)

**Comment by sam9116** [comment]
@jeevikasirwani I already did, just something for you to keep in mind next time

**Comment by jeevikasirwani** [comment]
> @jeevikasirwani I already did, just something for you to keep in mind next time

ok noted!
